import org.junit.Test;

import com.test.nio.CompareFileIO;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Administrator' at '17-4-18 上午10:56' with Gradle 2.11
 *
 * @author Administrator, @date 17-4-18 上午10:56
 */
public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
	@Test public void testIO () {
		String FILE_PATH = "E:/testFile/java.txt";
		String FILE_OUT_PATH = "E:/testFile/java_out.txt";
		 long time1 = CompareFileIO.getTime() ;
	        // readFileByByte(FILE_PATH);// 8734,8281,8000,7781,8047
	        // readFileByCharacter(FILE_PATH);// 734, 437, 437, 438, 422
	        // readFileByLine(FILE_PATH);// 110, 94,  94,  110, 93
		 	CompareFileIO.readFileByBybeBuffer(FILE_PATH,FILE_OUT_PATH);// 125, 78,  62,  78, 62
	        long time2 = CompareFileIO.getTime() ;
	        System.out.println(time2-time1);
	}
}
